-- MySQL Script generated by MySQL Workbench
-- Mon Jan 25 23:26:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sbb_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sbb_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sbb_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sbb_db` ;

-- -----------------------------------------------------
-- Table `sbb_db`.`passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sbb_db`.`passenger` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sbb_db`.`station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sbb_db`.`station` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `station_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sbb_db`.`train`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sbb_db`.`train` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `train_name` VARCHAR(45) NOT NULL,
  `seats` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sbb_db`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sbb_db`.`schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `arrival_time` DATETIME NULL DEFAULT NULL,
  `departure_time` DATETIME NULL DEFAULT NULL,
  `train_id` INT NOT NULL,
  `station_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_schedule_train1_idx` (`train_id` ASC) VISIBLE,
  INDEX `fk_schedule_station1_idx` (`station_id` ASC) VISIBLE,
  CONSTRAINT `fk_schedule_station1`
    FOREIGN KEY (`station_id`)
    REFERENCES `sbb_db`.`station` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_schedule_train1`
    FOREIGN KEY (`train_id`)
    REFERENCES `sbb_db`.`train` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 74
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sbb_db`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sbb_db`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `train_id` INT NOT NULL,
  `passenger_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ticket_train1_idx` (`train_id` ASC) VISIBLE,
  INDEX `fk_ticket_passenger1_idx` (`passenger_id` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_passenger1`
    FOREIGN KEY (`passenger_id`)
    REFERENCES `sbb_db`.`passenger` (`id`),
  CONSTRAINT `fk_ticket_train1`
    FOREIGN KEY (`train_id`)
    REFERENCES `sbb_db`.`train` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sbb_db`.`train_has_passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sbb_db`.`train_has_passenger` (
  `train_id` INT NOT NULL,
  `passenger_id` INT NOT NULL,
  PRIMARY KEY (`train_id`, `passenger_id`),
  INDEX `fk_train_has_passenger_passenger1_idx` (`passenger_id` ASC) VISIBLE,
  INDEX `fk_train_has_passenger_train1_idx` (`train_id` ASC) VISIBLE,
  CONSTRAINT `fk_train_has_passenger_passenger1`
    FOREIGN KEY (`passenger_id`)
    REFERENCES `sbb_db`.`passenger` (`id`),
  CONSTRAINT `fk_train_has_passenger_train1`
    FOREIGN KEY (`train_id`)
    REFERENCES `sbb_db`.`train` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
