-- MySQL Script generated by MySQL Workbench
-- Sat Jan  9 20:50:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sbb_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sbb_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sbb_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sbb_db` ;

-- -----------------------------------------------------
-- Table `sbb_db`.`passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sbb_db`.`passenger` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `gender` VARCHAR(1) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sbb_db`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sbb_db`.`role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sbb_db`.`access_rights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sbb_db`.`access_rights` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT UNSIGNED NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_access_rights_role1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_access_rights_passenger1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_access_rights_passenger1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sbb_db`.`passenger` (`id`),
  CONSTRAINT `fk_access_rights_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `sbb_db`.`role` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sbb_db`.`station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sbb_db`.`station` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `station_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sbb_db`.`path`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sbb_db`.`path` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `station_from` INT NOT NULL,
  `station_to` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_path_station1_idx` (`station_from` ASC) VISIBLE,
  INDEX `fk_path_station2_idx` (`station_to` ASC) VISIBLE,
  CONSTRAINT `fk_path_station1`
    FOREIGN KEY (`station_from`)
    REFERENCES `sbb_db`.`station` (`id`),
  CONSTRAINT `fk_path_station2`
    FOREIGN KEY (`station_to`)
    REFERENCES `sbb_db`.`station` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sbb_db`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sbb_db`.`reservation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `passenger_code` INT NOT NULL,
  `reservation_status` VARCHAR(45) NOT NULL,
  `date_of_travel` DATETIME NOT NULL,
  `date_reservation_made` DATETIME NOT NULL,
  `number_in_party` INT NOT NULL,
  `from_station_id` INT NOT NULL,
  `to_station_id` INT NOT NULL,
  `passenger_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservation_passenger1_idx` (`passenger_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_passenger1`
    FOREIGN KEY (`passenger_id`)
    REFERENCES `sbb_db`.`passenger` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sbb_db`.`train`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sbb_db`.`train` (
  `train_number` INT NOT NULL AUTO_INCREMENT,
  `train_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`train_number`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sbb_db`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sbb_db`.`schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `arrival_time` DATETIME NOT NULL,
  `departure_time` DATETIME NOT NULL,
  `path_id` INT NOT NULL,
  `train_number` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_schedule_path_idx` (`path_id` ASC) INVISIBLE,
  INDEX `fk_schedule_train1_idx` (`train_number` ASC) VISIBLE,
  CONSTRAINT `fk_schedule_path`
    FOREIGN KEY (`path_id`)
    REFERENCES `sbb_db`.`path` (`id`),
  CONSTRAINT `fk_schedule_train1`
    FOREIGN KEY (`train_number`)
    REFERENCES `sbb_db`.`train` (`train_number`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sbb_db`.`train_capacity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sbb_db`.`train_capacity` (
  `train_number` INT NOT NULL,
  `railway_carriage_number` INT NOT NULL,
  `seat_number` INT NOT NULL,
  INDEX `train_capacity_train_number_foreign` (`train_number` ASC) VISIBLE,
  CONSTRAINT `train_capacity_train_number_foreign`
    FOREIGN KEY (`train_number`)
    REFERENCES `sbb_db`.`train` (`train_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sbb_db`.`seat_reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sbb_db`.`seat_reservation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reservation_id` INT UNSIGNED NOT NULL,
  `seat_number_reserved` INT NOT NULL,
  `railway_carriage_number_reserved` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seat_reservation_reservation1_idx` (`reservation_id` ASC) VISIBLE,
  INDEX `fk_seat_number` (`seat_number_reserved` ASC) VISIBLE,
  INDEX `fk_railway_carriage_number_idx` (`railway_carriage_number_reserved` ASC) VISIBLE,
  CONSTRAINT `fk_railway_carriage_number`
    FOREIGN KEY (`railway_carriage_number_reserved`)
    REFERENCES `sbb_db`.`train_capacity` (`train_number`),
  CONSTRAINT `fk_seat_number`
    FOREIGN KEY (`seat_number_reserved`)
    REFERENCES `sbb_db`.`train_capacity` (`train_number`),
  CONSTRAINT `fk_seat_reservation_reservation1`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `sbb_db`.`reservation` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
